### ISSUE TITLE
EOF check is incorrect as of last commit

### ISSUE THREAD

**Issue by krissell** [sapienzaapps/apns2#1]
https://github.com/sapienzaapps/apns2/blob/master/client.go#L189
errors.Is(err, io.EOF) ==> !errors.Is(err, io.EOF)

The last commit reversed the existing logic

**Comment by Enrico204** [comment]
You're right! There is a typo in last commit! I'll fix it ASAP :+1:

**Comment by Enrico204** [comment]
Done in [918a794](https://github.com/sapienzaapps/apns2/commit/918a79410b6ff0da9a0cd7f4f64312127508d99e)
